<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>monorepo</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>shared-resources</module>
        <module>constraint-checker</module>
        <module>oracle-cli</module>
        <module>natural-language-oracle</module>
        <module>fault-injection</module>
        <module>question-generation</module>
        <module>test-runner</module>
    </modules>
</project>
