export const Action = {
  TYPED: "TYPED",
  CHECK: "CHECK",
  SEND: "SEND",
  CLICKED: "CLICKED",
  OPENED: "OPENED",
  CLOSED: "CLOSED",
  RESET: "RESET",
  BUILD: "BUILD",
  EXECUTE: "EXECUTE",
  CANCEL: "CANCEL",
  PASTED: "PASTED"
};

export const Component = {
  AI_AGENT: "AI_AGENT",
  CHAT_APP: "CHAT_APP",
  BUTTON: "BUTTON",
  MODAL: "MODAL",
  ORACLE: "ORACLE",
  TAB: "TAB",
  CODE_EDITOR: "CODE_EDITOR",
  TEST_CASE: "TEST_CASE",
  TESTS: "TESTS",
};
