spring.application.name=p4p-logging
spring.data.mongodb.database=probeable-problems-logging
spring.data.mongodb.uri=${MONGO_DB_URL}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
server.port=8081
