spring.application.name=p4p
spring.data.mongodb.database=probeable-problems
spring.data.mongodb.uri=${MONGO_DB_URL}
spring.ai.openai.api-key=${SPRING_AI_OPENAI_API_KEY}
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
