spring.application.name=p4p

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini

# spring.ai.openai.chat.options.response-format.type=JSON_SCHEMA
# spring.ai.openai.chat.options.response-format.name=MySchemaName
# spring.ai.openai.chat.options.response-format.schema={"type": "object","properties": {"is_valid": { "type": "boolean" },"explanation": { "type": "string" }},"required": ["is_valid", "explanation"],"additionalProperties": false}
# spring.ai.openai.chat.options.response-format.strict=true